### ISSUE TITLE
[scenejs/ionic] issue with --aot / --prod builds 

### ISSUE THREAD

**Issue by devHamza** [daybrush/scenejs#28]
**Describe the bug**

Hi, Thank you for this amazing library ! 
I'm using it in my cordova/ionic 4 application, everything works as expected in my dev environment, however I'm facing an issue with the staging build when I pass "--aot" argument to the build cmd :  ionic-app-scripts build --aot --minifyjs --minifycss --optimizejs
The error is 
Error: Cannot find module "."

**To Reproduce**
1. Create an Ionic 3 project 
2. Add scenejs as npm dependency 
3. build project with --aot --minifyjs --minifycss --optimizejs
4. See error Error: Cannot find module "."

**Expected behavior**
App works as expected in prod and dev env 

**Versions :**
  - test device : iPhone 7 / iPhone XR
 - ionic 4.3.1 
 - cordova : 8.1.2 (cordova-lib@8.1.1)
 - @ionic/app-scripts :  3.1.11

**Additional context**
N/a

**Comment by daybrush** [comment]
@devHamza
Hello devHamza.
First of all, thank you very much for reporting the issue.

We don't have enough information to solve the error. Can you show me the error stack when it comes with it?

Oh, and now the version of scenejs@1.0.1 has been released, and I don't know if this problem has been resolved.

**Comment by daybrush** [comment]
@devHamza 

Isn't `@ionic/app-scripts` unique to ionic3?

First, the following error occurs to execute the script in ionic4.

![스크린샷 2019-05-31 오전 3 36 02](https://user-images.githubusercontent.com/3433062/58655527-41bee880-8355-11e9-80f3-f8466a2cf744.png)

**Comment by devHamza** [comment]
@daybrush Thanks for responding, I'll try to create a boilerplate ionic stack with the error as soon as I can. 
For the stack trace, I don't have much informations, the build pass successfully, the only error I'm having is this : 

<img width="364" alt="errror" src="https://user-images.githubusercontent.com/7511173/58668393-46b97300-8328-11e9-9f42-e4a5199a4e06.png">
 
Regards

**Comment by daybrush** [comment]
@devHamza 

Can you show me the package.json file and the file with Scenejs applied?

**Comment by devHamza** [comment]
Hello @daybrush, 

I created an empty ionic project on witch you can reproduce the issue by executing 
ionic cordova build ios --minifyjs --minifycss --optimizejs --prod --aot 

=> https://github.com/devHamza/ionic-scenejs-bug 

I also found that there is a build error with the version 2.6.2 of typescript (it works well with the 3.4.5)
<img width="1039" alt="screenshot" src="https://user-images.githubusercontent.com/7511173/58699517-35568200-838d-11e9-8ad6-fda30d0c8cef.png">

PS: sorry for the version of ionic, I was talking about the ionic cli version, but the project is an ionic 3 stack. 

Regards

**Comment by devHamza** [comment]
I can reproduce it with ionic cordova build ios **--aot**, now I'm having more relevant stack trace : 

<img width="432" alt="stack" src="https://user-images.githubusercontent.com/7511173/58700467-9ed79000-838f-11e9-8e4b-58c43a65cc94.png">

**Comment by daybrush** [comment]
@devHamza 

Maybe I found a solution.

@ionic/app-scripts@3 do not support typescript 2.8 or higher.
but Scene.js are available from 2.8. 

It's okay, though.

Downgrade the typescript to 2.7.

and  add tsconfig options
```json
{
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
}
```
* tsconfig.json
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
````

Then I'll do it.

**Comment by devHamza** [comment]
It works ! Thanks a lot 🙏

**Comment by daybrush** [comment]
@devHamza 

I'm glad the problem is solved. If you have any problems or questions, please write issue.
