### ISSUE TITLE
How to control playback in react

### ISSUE THREAD

**Issue by saga7878** [daybrush/scenejs#46]
Scenejs is great，To use react-scenejs in react, I have to set ref on the component to call play() to control playback. Is there any other way?

**Comment by daybrush** [comment]
@jiameng123 

There is an `autoplay` prop that can be played right when it is first mounted.
https://github.com/daybrush/scenejs/tree/master/packages/react-scenejs#props


Is this what you're saying?
```js
import { Scene } from "react-scenejs";

render() {
    retrun <Scene .....  autoplay>.....</Scene>;
}
```

**Comment by saga7878** [comment]
> @jiameng123
> 
> There is an `autoplay` prop that can be played right when it is first mounted.
> https://github.com/daybrush/scenejs/tree/master/packages/react-scenejs#props
> 
> Is this what you're saying?
> 
> ```js
> import { Scene } from "react-scenejs";
> 
> render() {
>     retrun <Scene .....  autoplay>.....</Scene>;
> }
> ```

  I tried autoplay, but it only works when I first mount it. I want to have a method similar to scene.play(), for example by clicking the button to play the animation.

Now I use the following method to control when the Scene works. Is there any other way?
@daybrush 
  ````
   <Scene ref="sc"> </Scene>
    this.ref.current.play()
 ````

**Comment by daybrush** [comment]
@jiameng123 
Sorry. There is no way to play/pause other than to use ref.

**Comment by saga7878** [comment]
@daybrush  
Thank you very much for your answer, Scenejs is great.

**Comment by daybrush** [comment]
@jiameng123 
Thank you for using Scene.js :)
