### ISSUE TITLE
Errors when using NgxSceneModule

### ISSUE THREAD

**Issue by wSedlacek** [daybrush/scenejs#50]
**Describe the bug**
When attempting to import NgxSceneModule there are a few issues noticed.

1) Error at run time:
![Screen Shot 2019-09-09 at 20 03 56](https://user-images.githubusercontent.com/8206108/64576179-00b77680-d33d-11e9-9a50-985f74345cbb.png)

2) Error in VS Code
![Screen Shot 2019-09-09 at 20 01 49](https://user-images.githubusercontent.com/8206108/64576191-1036bf80-d33d-11e9-8b17-a8873157ef36.png)

**To Reproduce**
1. ng new <name>
2. yarn add ngx-scenejs
3. Add lines to app.module.ts:
```ts
import { NgxSceneModule } from 'ngx-scenejs';

@NgModule({
  imports: [
    NgxSceneModule
  ],
})
export class AppModule { }
```
4. ng serve (Error #1 will show in console)

5. Enable VS Code extension Angular Language Service - https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
6. Add lines to app.component.html:
```ts
<ngx-scene></ngx-scene>
```
7. Error #2 will show in VS Code

**Expected behavior**
When importing an Angular Module it shouldn't have errors at run time nor when using the Angular Lange Service.

**Screenshots**
(See Above)

**Desktop (please complete the following information):**
 - OS: macOS 10.13
 - Browser: Google Chrome 76
 - IDE: VS Code 1.38
 - Extensions: Angular Language Service 0.802.3

**Additional context**
I have tested with ngx-scenejs 1.1.0 and 1.0.1, from my test the behavior remains the sanme on both versions.

In your examples I have noticed that you have imported `NgxSceneComponent` directly into AppModule then added it to then declarations. While this does not have any errors at run time the Angular Language Service still produces error #2 and this does not match the way other Angular dependancies are imported.

I have also noticed that node_modules/ngx-scenejs/declaritions/ngx-scene.module.d.ts appears to be empty.
```ts
export declare class NgxSceneModule {
}
```

**Comment by daybrush** [comment]
I'm sorry. I'll check it.

Would you like to use it temporarily?

```js
import { NgxSceneComponent, NgxSceneItemComponent } from "ngx-scenejs";


@NgModule({
  declarations: [
    NgxSceneComponent,
  ],
})
```

**Comment by wSedlacek** [comment]
No worries at all! Thank you for getting back with me.

Using this temporarily solution does allow the code to run, however error #2 with the Angular Language Service extension still exist.

**Comment by daybrush** [comment]
@wSedlacek 

ngx-scenejs 1.1.1 is released. Please check again.

Thank you

**Comment by wSedlacek** [comment]
Great work it seems to be working now! Thank you very much for the quick fix.
