### ISSUE TITLE
typing - effects is undefined in Vue-scenejs

### ISSUE THREAD

**Issue by wnghdcjfe** [daybrush/scenejs#58]
**Describe the bug**
```
  import {
    zoomIn, 
    typing
  } from "@scenejs/effects";
...
    mounted(){
      console.log("effects : ", typing)
      console.log("effects : ", zoomIn)
      /*
      effects :  undefined
      effects :  ƒ zoomIn(_a) {
  var _b = _a === void 0 ? {} : _a,
      _c = _b.from,
      from = _c === void 0 ? 0 : _c,
      _d = _b.to,
      to = _d === void 0 ? 1 : _d;

  return set(["transform", "scale"], [f…
      */
```
 
and My pacakge.json
```js
  "devDependencies": {
    "@daybrush/builder": "^0.1.1",
    "@scenejs/effects": "^0.1.0",
```
When I tried to typing-effect
[typing-effect](https://daybrush.com/scenejs-effects/release/latest/doc/effects.html#.typing)
But it is not working. 
Is it diffrent version vue-scenejs and scenejs?

**Comment by wnghdcjfe** [comment]
I knew it this is version problem, I install latest effect module, and fixed it
But, It is necessary to update effect module version following by "scene js" version

**Comment by daybrush** [comment]
`@scenejs/effects`'s version is 1.0.1.

Check it again. Thank you :)

**Comment by wnghdcjfe** [comment]
No, @scenejs/effects's version is 1.0.1. But Vue-scenejs package.json's  @scenejs/effects's version  is 0.1.0

**Comment by daybrush** [comment]
@wnghdcjfe 
Simply because version 0.1.0 is the devDependencies of vue-scenejs. This is for testing purposes, so you can use the latest version.
