### ISSUE TITLE
Easing option per keyframe

### ISSUE THREAD

**Issue by tjebbemarchand** [daybrush/scenejs#88]
## Environments
* Framework name: ReactJS
* Framework version: 18.1.0
* React scene component version: 1.1.0
* Testable Address(optional):

## Description
Is it possible to add an easing option per keyframe? Now I have an options object with the easing option, but that is over the whole animation.

` {
    ".headline_subline_button_gSla8FyLX.format_336x280": {
        "0": {
            "visibility": "visible",
            "transform": "translate(0px, 0px)"
        },
        "5": {
            "visibility": "visible"
        },
        "0.7": {
            "transform": "translate(100px, 0px)"
        },
        "options": {
            "easing": "cubic-bezier(0,1.29,1,-0.27)"
        }
    }
}`

**Comment by daybrush** [comment]
@tjebbemarchand 


Just set the easing on each frame.

`playCSS` works normally, but there is a bug in the play function.

But it will be fixed soon.


https://codepen.io/daybrush/pen/qBQWKzW

**Comment by daybrush** [comment]
@tjebbemarchand 

`scenejs`'s new version is released.

Just set the easing on each frame.


https://codepen.io/daybrush/pen/qBQWKzW

**Comment by tjebbemarchand** [comment]
@daybrush 

Awesome! Thank you for your quick reply. That is exacly what I need. I will update scene to the new version in my project.
